# fly.toml app configuration file generated for app-red-violet-9766 on 2024-11-18T07:18:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'app-red-violet-9766'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = "canary"
