name: Health Check Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Run every 5 minutes

env:
  URL: https://app-red-violet-9766.fly.dev

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ env.URL }}
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
      - name: Notify on success
        uses: tsickert/discord-webhook@v5.3.0
        if: success()
        with:
          embed-color: 6144854
          username: Github Actions
          content: A new version of Pokedex has been deployed
          embed-description: "URL: ${{ needs.simple_deployment_pipeline.outputs.deploy_url }}"
          embed-author-name: "by ${{ github.actor }}"
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notify on failure
        if: failure()
        uses: tsickert/discord-webhook@v5.3.0
        with:
          embed-color: 14701393
          content: Pokedex build failed
          embed-description: "Last commit: ${{ github.event.head_commit.url }} didn't pass the build checks"
          embed-author-name: "by ${{ github.event.head_commit.author.name }}"
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}          