name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:

  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test

      # Playwright will run the production server and run the e2e tests
      # the build should be available before running the tests
      - run: npx playwright install --with-deps
      - name: Run e2e tests with Playwright
        run: npm run test:e2e